# Generated by Django 5.1 on 2024-08-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('age', models.ImageField(upload_to='')),
                ('dob', models.DateField()),
                ('bed_no', models.ImageField(upload_to='')),
                ('problem', models.TextField(max_length=500)),
                ('doa', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
