# Generated by Django 5.1 on 2024-08-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdata',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pdata',
            name='bed_no',
            field=models.IntegerField(),
        ),
    ]
